from typing import TypedDict, List, Dict, Any, Optional

class AgentState(TypedDict):
    # Incident inputs
    incident_db_id: int
    ticket_id: str
    title: str
    description: str
    incident_template: Optional[Dict[str, Any]]
    target_repo: Optional[str]
    target_branch: Optional[str]
    target_app_path: Optional[str]
    application_log_path: Optional[str]
    
    # Shared Investigation Context (generated by Planner)
    shared_context: Optional[Dict[str, Any]]
    
    # Coordinated Parallel Retrieval Evidence
    gitlab_evidence: Optional[Dict[str, Any]]
    cicd_evidence: Optional[Dict[str, Any]]
    log_evidence: Optional[Dict[str, Any]]
    
    # Synthesis & RCA
    root_cause: Optional[str]
    confidence_score: Optional[int] # 0-100
    affected_file: Optional[str]
    evidence_chain: Optional[List[str]]
    pinned_commit_sha: Optional[str]  # The single commit SHA all agents agree on
    
    # Patch Proposals & Validation
    patch_explanation: Optional[str]
    target_content: Optional[str]
    replacement_content: Optional[str]
    patch_diff: Optional[str]
    validation_passed: Optional[bool]
    validation_logs: Optional[str]
    validation_retry_count: int
    
    # Output MR & RCA Report
    gitlab_mr_url: Optional[str]
    rca_report: Optional[str]
    
    # Investigation Timeline — list of {time, label} dicts for UI display
    investigation_timeline: Optional[List[Dict[str, str]]]
    
    # Execution status (e.g. "PLANNING", "RETRIEVING", "FUSING", "PATCHING", "VALIDATING", "COMPLETED", "FAILED")
    current_step: str
